version: '3.8'

services:
  verdaccio:
    image: verdaccio/verdaccio
    container_name: 'routineless-verdaccio'
    networks:
      - node-network
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - '4873:4873'
    volumes:
      - './verdaccio/conf:/verdaccio/conf'
  localstack:
    container_name: 'routineless-localstack_main'
    image: localstack/localstack
    ports:
      - '127.0.0.1:4566:4566' # LocalStack Gateway
      - '127.0.0.1:4510-4559:4510-4559' # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      # - '../tmp/localstack/volume:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
networks:
  node-network:
    driver: bridge
